# Generated by Django 2.2.18 on 2021-02-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postimage',
            field=models.ImageField(default='test', upload_to='images', verbose_name='postimage'),
            preserve_default=False,
        ),
    ]
