# Generated by Django 2.2.18 on 2021-02-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210204_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postimage',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='postimage'),
        ),
    ]
