# Generated by Django 2.2.18 on 2021-02-05 03:00

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='test'),
            preserve_default=False,
        ),
    ]
