# Generated by Django 2.2.18 on 2021-02-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
