# Generated by Django 2.2.18 on 2021-02-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_post_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
